spring.application.name=Job-Portal
spring.data.mongodb.auto-index-creation=true
spring.data.mongodb.uri=mongodb\://localhost\:27017/jobportal


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ahirevivek100@gmail.com
spring.mail.password=zwxgannhphjvgkih
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.main.allow-bean-definition-overriding=true
spring.main.allow-circular-references=true

jwt.secret=Base64EncodedSecretKeyAtLeast32CharsLongVariable

USER_FOUND=User has registered already .
USER_NOT_FOUND=User is not registerd .
INVALID_CREDENTIALS=Invalid Credentials .
OTP_NOT_FOUND=OTP is expired .
OTP_INCORRECT=OTP is incorrect .

JOB_NOT_FOUND=Job not Found.
JOB_APPLIED_ALREADY=Job applied already.
